laika.title = "mirra"

laika.navigationOrder = [
  introduction.md
  getting-started.md
  combinators.md
  composing-repositories.md
  doobie.md
  skunk.md
  munit.md
  zio-test.md
  cats-effect.md
  zio.md
]
